# Generated by Django 4.2.7 on 2023-11-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
