# Generated by Django 4.2.7 on 2023-11-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_userprofile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='extra_photos',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photos',
            field=models.ManyToManyField(blank=True, related_name='profile_photos', to='authentication_app.image'),
        ),
    ]
