# Generated by Django 4.2.7 on 2023-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_remove_userprofile_extra_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photos',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extra_photos',
            field=models.ManyToManyField(blank=True, to='authentication_app.image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
