# Generated by Django 4.2.7 on 2023-11-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_remove_userprofile_profile_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bedroom',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hallroom',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kitchen',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10),
        ),
    ]
