# Generated by Django 4.2.7 on 2023-11-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0007_rename_location_userprofile_location_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
